# Test Script for Standalone Executable
# This script provides instructions for testing the PortalFrameAnalysis.exe

print("=== Portal Frame Analysis Executable Test ===")
print()
print("1. Navigate to the 'dist' folder in your file explorer")
print("2. Double-click on 'PortalFrameAnalysis.exe'")
print("3. The application should start with the modern UI")
print("4. Test basic functionality:")
print("   - Enter some geometry values")
print("   - Select steel sections from dropdowns")
print("   - Click 'Hesapla ve Çiz' to run analysis")
print("   - Click 'Tahkik Et' to verify sections")
print("   - Click 'Optimize Et' to run optimization")
print()
print("If the executable opens and works correctly, the build is successful!")
print()
print("The executable includes:")
print("- Complete portal frame analysis")
print("- Steel section database (43 sections)")
print("- Optimization algorithms")
print("- Modern CustomTkinter UI")
print("- Matplotlib plotting")
print("- All required dependencies")
print()
print("File location: C:\\Users\\AVM1\\PORTAL\\dist\\PortalFrameAnalysis.exe")
print("File size: ~25.8 MB")
print()
print("=== Distribution Notes ===")
print("- This single .exe file can be distributed without Python")
print("- No additional installations required on target machines")
print("- Works on Windows 10/11 (64-bit)")
print("- First startup may take a few seconds")
